### ISSUE TITLE
Alphanumeric string support

### ISSUE THREAD

**Issue by delehef** [bash/fmtastic#18]
Hi!

Would you be open to add support for general alphanumerical string sub/super-scripting?

It would prove very useful for hex strings display.

**Comment by delehef** [comment]
Nevermind, the unicode blocks are actually missing quite a few letters.

**Comment by tautropfli** [comment]
> It would prove very useful for hex strings display.

> Nevermind, the unicode blocks are actually missing quite a few letters.

I actually looked into this too, but came to the same conclusion :/

Binary and octal support would be possible thought :)
