### ISSUE TITLE
Doc links look like invalid markdown to me

### ISSUE THREAD

**Issue by janhohenheim** [bash/fmtastic#3]
https://github.com/bash/fmtastic/blob/7a035a0d91bc55d8434cc98329dacd91ddaa4fe1/src/sub_superscript.rs#L6

**Comment by tautropfli** [comment]
That's correct markdown, the left is a label, the right is a link definition. E.g.

```markdown
Here is a [link].
Here is a [link with a different label][link].

[link]: https://example.com
```

**Comment by janhohenheim** [comment]
Use the following, it's less convoluted:
```md
[`Display`](std::fmt::Display)
```
