### ISSUE TITLE
Replace procedural code by a `fold`

### ISSUE THREAD

**Issue by janhohenheim** [bash/fmtastic#8]
https://github.com/bash/fmtastic/blob/7a035a0d91bc55d8434cc98329dacd91ddaa4fe1/src/sub_superscript.rs#L51

**Comment by tautropfli** [comment]
1. It would be a iter::successors, not a fold :)
   <details>

    ```rust
      iter::successors(Some(1), |exponent| exponent.checked_mul(BASE))
          .last()
          .unwrap_or_else(|| unreachable!())
    ```

   </details>
3. Iterator methods are not const :/
